# %% [markdown]
# # Album Art Pipeline: End-to-End Vetting
# 
# This notebook validates the entire Visual Layer pipeline, from fetching data to on-device simulation.
# 
# **Architecture:**
# 1. **Ingestion:** Manifest -> Cover Art Archive (CAA).
# 2. **Tokenizer:** 128x128 Image -> VQ-VAE -> 16x16 Tokens.
# 3. **Storage:** Tokens -> `art.bin` (Fixed Layout).
# 4. **Decoding:** `art.bin` + Codebook -> Image (iOS Simulation).

# %% 
import os
import sys
import torch
import requests
import pandas as pd
import numpy as np
import struct
from PIL import Image
from io import BytesIO
from torchvision import transforms
import matplotlib.pyplot as plt

# Add src to path
sys.path.append(os.path.join(os.getcwd(), '../src'))
from model import VQVAE

# Configuration
MANIFEST_PATH = "data/album_manifest.csv"
CACHE_DIR = "data/test_covers"
MODEL_PATH = "release/visual_encoder.pth"

if not os.path.exists(CACHE_DIR):
    os.makedirs(CACHE_DIR)

# %% [markdown]
# ## 1. Ingestion: The Bridge Check
# We load the manifest generated by the Metadata Pipeline and verify we can fetch images.
# We pick 5 random albums to serve as our "Test Set".

# %% 
def verify_ingestion():
    print(f"--- 1. Ingestion Verification ---")
    if not os.path.exists(MANIFEST_PATH):
        print("⚠️ Manifest not found. Using DUMMY data.")
        df = pd.DataFrame([
            {"album_index": 0, "release_uuid": "e014041d-3843-4e8c-859a-f33c373a0c5c", "album_name": "Dark Side of the Moon"},
            {"album_index": 1, "release_uuid": "32130386-0b44-4638-9226-0a2569e5d614", "album_name": "Abbey Road"},
            {"album_index": 2, "release_uuid": "INVALID-UUID-TEST", "album_name": "Missing Art Test"}
        ])
    else:
        df = pd.read_csv(MANIFEST_PATH)
        print(f"Loaded Manifest: {len(df):,} albums.")
        # Pick 5 valid UUIDs (length > 4) to ensure they aren't N/A
        valid_df = df[df['release_uuid'].astype(str).str.len() > 10]
        df = valid_df.sample(5)

    downloaded_paths = []
    
    for _, row in df.iterrows():
        uuid = row['release_uuid']
        name = str(row['album_name'])[:30]
        
        url = f"https://coverartarchive.org/release/{uuid}/front-250"
        save_path = os.path.join(CACHE_DIR, f"{uuid}.jpg")
        
        print(f"Fetching: {name} ({uuid})...")
        try:
            r = requests.get(url, timeout=5)
            if r.status_code == 200:
                with open(save_path, "wb") as f:
                    f.write(r.content)
                downloaded_paths.append((row['album_index'], save_path))
                print(f"  ✅ Downloaded ({len(r.content)/1024:.1f} KB)")
            else:
                print(f"  ❌ Failed (Status {r.status_code}) - Expected for invalid UUIDs")
        except Exception as e:
            print(f"  ❌ Error: {e}")

    return downloaded_paths

test_samples = verify_ingestion()

# %% [markdown]
# ## 2. The Tokenizer: Overfit Training Check
# We initialize the VQ-VAE model and train it on our 5 downloaded samples.
# This "Overfit Test" proves the model can actually learn and reconstruct images.
# Instead of random noise, we expect to see clear reconstructions at the end.

# %%
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Hyperparameters
NUM_HIDDENS = 128
NUM_RESIDUAL_LAYERS = 2
NUM_RESIDUAL_HIDDENS = 32
NUM_EMBEDDINGS = 1024
EMBEDDING_DIM = 64
COMMITMENT_COST = 0.25
TEST_MODEL_PATH = "/tmp/overfit_encoder.pth"

model = VQVAE(NUM_HIDDENS, NUM_RESIDUAL_LAYERS, NUM_RESIDUAL_HIDDENS,
              NUM_EMBEDDINGS, EMBEDDING_DIM, COMMITMENT_COST).to(device)

# Transform pipeline
transform = transforms.Compose([
    transforms.Resize((128, 128)),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])

# Prepare Data for Training
if test_samples:
    print(f"--- 2. Overfit Training on {len(test_samples)} images ---")
    
    # Pre-load tensors
    images = []
    for _, path in test_samples:
        img = Image.open(path).convert('RGB')
        images.append(transform(img))
    
    batch = torch.stack(images).to(device)
    
    optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)
    model.train()
    
    # Train for 100 steps (enough to memorize 5 images)
    print("Training...", end="")
    for i in range(100):
        optimizer.zero_grad()
        vq_loss, data_recon, perplexity = model(batch)
        recon_error = torch.mean((data_recon - batch)**2)
        loss = recon_error + vq_loss
        loss.backward()
        optimizer.step()
        
        if (i+1) % 20 == 0:
            print(f" {i+1}...", end="")
    
    print(f"\nFinal Loss: {loss.item():.4f}")
    
    # Save to /tmp
    torch.save(model.state_dict(), TEST_MODEL_PATH)
    model.eval()
else:
    print("⚠️ No samples to train on.")

# %% [markdown]
# ## 3. Binary Packing (Simulation)
# We take our downloaded images and pack them into a mini `art.bin`.
# This tests the `build_index.py` logic: encoding -> uint16 -> flat binary.

# %%
TEST_BIN = "/tmp/test_art.bin"

def pack_mini_binary(samples):
    print(f"\n--- 3. Packing Binary ({TEST_BIN}) ---")
    
    # Sort by index to simulate real DB structure
    samples.sort(key=lambda x: x[0])
    
    # We need to fill gaps. If we have Index 0 and Index 5, we must write placeholders for 1, 2, 3, 4.
    max_idx = samples[-1][0]
    sample_map = {idx: path for idx, path in samples}
    
    packed_count = 0
    with open(TEST_BIN, "wb") as f:
        for idx in range(max_idx + 1):
            if idx in sample_map:
                # 1. Load & Transform
                img = Image.open(sample_map[idx]).convert('RGB')
                tensor = transform(img).unsqueeze(0).to(device)
                
                # 2. Inference
                with torch.no_grad():
                    z = model._encoder(tensor)
                    z = model._pre_vq_conv(z)
                    _, _, _, indices = model._vq_vae(z)
                    
                    # Flatten [1, 16, 16] -> [256]
                    tokens = indices.view(-1).cpu().numpy().astype(np.uint16)
                
                # 3. Write
                f.write(tokens.tobytes())
                packed_count += 1
            else:
                # Write Placeholder (FFFF)
                placeholder = np.full((256,), 65535, dtype=np.uint16)
                f.write(placeholder.tobytes())
                
    print(f"Packed {max_idx + 1} slots (including gaps).")

if test_samples:
    pack_mini_binary(test_samples)
else:
    print("No samples to pack.")
# %% [markdown]
# ## 4. iOS Simulator (The Decoder)
# This is the critical test. We act like the iPhone:
# 1. Open `art.bin`.
# 2. Seek to `Index * 512`.
# 3. Read tokens.
# 4. Look up vectors from the Codebook.
# 5. Decode.

# %% 
def ios_decoder_simulation(target_idx):
    print(f"\n--- 4. iOS Simulation for Index {target_idx} ---")
    
    # 1. Read Tokens from Binary
    with open(TEST_BIN, "rb") as f:
        offset = target_idx * 512 # 256 tokens * 2 bytes
        f.seek(offset)
        data = f.read(512)
        
        if not data or len(data) < 512:
            print("Index out of bounds.")
            return

        tokens = np.frombuffer(data, dtype=np.uint16)
        
        # Check for placeholder
        if tokens[0] == 65535:
            print("Found Placeholder (No Art).")
            return

    print(f"Read 256 tokens. First 10: {tokens[:10]}")

    # 2. Reconstruct Tensor from Codebook
    # (Simulating C++ Lookup)
    codebook = model._vq_vae._embedding.weight.data # [1024, 64]
    
    # Lookup: [256] -> [256, 64]
    indices_tensor = torch.from_numpy(tokens.astype(np.int64)).to(device)
    quantized_flat = torch.index_select(codebook, 0, indices_tensor)
    
    # Reshape: [1, 64, 16, 16] (CoreML Input Format)
    # Note: Torch stores as [Batch, Channel, H, W]
    quantized = quantized_flat.view(1, 16, 16, 64).permute(0, 3, 1, 2)
    
    # 3. Decode
    with torch.no_grad():
        recon = model._decoder(quantized)
        
    # 4. Visualize
    recon_img = recon.squeeze(0).cpu() * 0.5 + 0.5 # Un-normalize
    recon_pil = transforms.ToPILImage()(recon_img)
    
    plt.figure(figsize=(10, 5))
    
    # Original
    original_path = [p for i, p in test_samples if i == target_idx][0]
    plt.subplot(1, 2, 1)
    plt.title("Original (250px)")
    plt.imshow(Image.open(original_path))
    plt.axis('off')
    
    # Reconstructed
    plt.subplot(1, 2, 2)
    plt.title("Decoded from art.bin (128px)")
    plt.imshow(recon_pil)
    plt.axis('off')
    plt.show()
    print("Displaying comparison...")

if test_samples:
    # Simulate decoding for the first valid sample
    ios_decoder_simulation(test_samples[0][0])
