# %% [markdown]
# # Album Art Ingestion Development
# This notebook validates the data ingestion strategy for the Visual Pipeline.
# We will:
# 1. Load the generated Album Manifest.
# 2. Test connectivity to the Cover Art Archive (CAA).
# 3. Handle 404s and Redirects properly.
# 4. Measure throughput to estimate full download time.

# %%
import os
import pandas as pd
import requests
import time
from concurrent.futures import ThreadPoolExecutor
from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt

# Path to the manifest generated by the Metadata Pipeline
MANIFEST_PATH = "data/album_manifest.csv"

# %% [markdown]
# ## 1. Load Manifest
# We load the mapping of `Album Index` -> `Release UUID`.

# %% 
if not os.path.exists(MANIFEST_PATH):
    print(f"Error: Manifest not found at {MANIFEST_PATH}")
    # Create a dummy dataframe for standalone testing
    df = pd.DataFrame([
        {"album_index": 0, "release_uuid": "e014041d-3843-4e8c-859a-f33c373a0c5c", "album_name": "Dark Side of the Moon"}, # Valid
        {"album_index": 1, "release_uuid": "00000000-0000-0000-0000-000000000000", "album_name": "Non-Existent Album"}   # Invalid
    ])
    print("Created DUMMY manifest for testing.")
else:
    df = pd.read_csv(MANIFEST_PATH)
    print(f"Loaded Manifest: {len(df):,} albums.")
    print(df.head())

# %% [markdown]
# ## 2. CAA Fetch Function
# The Cover Art Archive redirects `http://coverartarchive.org/release/{mbid}/front-250` to the actual image.

# %% 
def fetch_cover_art(mbid):
    url = f"https://coverartarchive.org/release/{mbid}/front-250"
    try:
        # We need to handle redirects manually or let requests do it (default=True)
        # Timeout is crucial to avoid hanging on slow IA servers
        r = requests.get(url, timeout=5) 
        
        if r.status_code == 200:
            return r.content, "FOUND"
        elif r.status_code == 404:
            return None, "MISSING"
        else:
            return None, f"ERROR_{r.status_code}"
            
    except Exception as e:
        return None, f"EXCEPTION_{str(e)}"

# %% [markdown]
# ## 3. Smoke Test
# We test with a few known IDs from the manifest.

# %% 
print("Running Smoke Test...")
test_samples = df.sample(5) if len(df) > 5 else df

for idx, row in test_samples.iterrows():
    mbid = row['release_uuid']
    name = row['album_name']
    
    start = time.time()
    img_data, status = fetch_cover_art(mbid)
    elapsed = time.time() - start
    
    print(f"[{status}] {name[:30]}... ({elapsed:.2f}s)")
    
    if status == "FOUND":
        # Verify it's a valid image
        try:
            img = Image.open(BytesIO(img_data))
            print(f"  -> Image Size: {img.size} | Mode: {img.mode}")
        except:
            print("  -> INVALID IMAGE DATA")

# %% [markdown]
# ## 4. Latency Estimation
# We fetch 20 items in parallel to see what kind of throughput we can expect.
# The CAA allows high concurrency, but we should be polite.

# %% 
def benchmark_download(samples):
    print(f"\nBenchmarking {len(samples)} downloads...")
    start_global = time.time()
    
    results = []
    with ThreadPoolExecutor(max_workers=8) as executor:
        futures = {executor.submit(fetch_cover_art, row['release_uuid']): row for _, row in samples.iterrows()}
        
        for future in futures:
            row = futures[future]
            data, status = future.result()
            results.append(status)
            
    elapsed = time.time() - start_global
    rate = len(samples) / elapsed
    print(f"Completed in {elapsed:.2f}s ({rate:.1f} req/s)")
    
    found = results.count("FOUND")
    missing = results.count("MISSING")
    errors = len(results) - found - missing
    
    print(f"Stats: Found: {found} | Missing: {missing} | Errors: {errors}")
    print(f"Estimated time for 850k albums: {(850000/rate)/3600:.1f} hours")

# Run benchmark on 50 items
if len(df) >= 50:
    benchmark_download(df.sample(50))
else:
    print("Not enough data to benchmark.")
