services:
  tokenizer:
    build:
      context: ..
      dockerfile: docker/Dockerfile.pipeline
    image: musicprint-pipeline:latest
    container_name: musicprint-tokenizer
    ports:
      - "8889:8888" # Jupyter Lab
    volumes:
      - ./src:/app/src
      - ./notebooks:/app/notebooks
      - ./release:/vol/release
      - musicprint_meta_data:/vol/data
      - musicprint_meta_cache:/vol/cache
    environment:
      - JUPYTER_TOKEN=musicprint
      - DB_HOST=mb_db
      - DB_PORT=5432
      - DB_USER=musicbrainz
      - DB_PASSWORD=musicbrainz
      - DB_NAME=musicbrainz_db
    stdin_open: true
    tty: true
    shm_size: '1gb'
    depends_on:
      - mb_db

  mb_db:
    image: postgres:16-alpine
    container_name: musicprint-mb-db
    shm_size: '1gb'
    environment:
      - POSTGRES_USER=musicbrainz
      - POSTGRES_PASSWORD=musicbrainz
      - POSTGRES_DB=musicbrainz_db
    volumes:
      - mb_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  mb_pgdata:
  musicprint_meta_data:
  musicprint_meta_cache: